apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: prom
spec:
  ports:
  - port: 8080
    targetPort : 3000
    name: http
  type: LoadBalancer
  selector:
    app.kubernetes.io/name : grafana
